---

services:
  go-pubsub-daemon:
    image: ${IMAGE}
    ports:
      - "${GO_PUBSUB_DAEMON_ADDR}:${GO_PUBSUB_DAEMON_PORT}:${GO_PUBSUB_DAEMON_PORT}"
    environment:
      - GO_PUBSUB_DAEMON_PORT
      - GO_PUBSUB_DAEMON_ADDR
